### ISSUE TITLE
secadm fails to install into a jail with a read-only basejail (affects ezjail)

### ISSUE THREAD

**Issue by umpc** [HardenedBSD/secadm#19]
`make install`
===> etc (install)
===> etc/rc.d (install)
install -o root  -g wheel -m 555  secadm  /usr/local/etc/rc.d//secadm
===> kmod (install)
install -o root -g wheel -m 555   secadm.ko /boot/kernel
install: /boot/kernel/secadm.ko: Read-only file system
*** Error code 71

Stop.
make[1]: stopped in /root/secadm/kmod
*** Error code 1

Stop.
make: stopped in /root/secadm

==========

`pkg install secadm`
Updating HardenedBSD repository catalogue...
HardenedBSD repository is up-to-date.
All repositories are up-to-date.
Checking integrity... done (0 conflicting)
The following 2 package(s) will be affected (of 0 checked):

New packages to be INSTALLED:
        secadm: 0.2.4
        libucl: 0.7.3_1

The process will require 381 KiB more space.

Proceed with this action? [y/N]: y
[io] [1/2] Installing libucl-0.7.3_1...
[io] [1/2] Extracting libucl-0.7.3_1: 100%
[io] [2/2] Installing secadm-0.2.4...
[io] [2/2] Extracting secadm-0.2.4:   0%
pkg: archive_read_extract(): Can't create '/boot/modules/secadm.ko'
[io] [2/2] Extracting secadm-0.2.4: 100%
[io] [2/2] Deleting files for secadm-0.2.4: 100%

==========

To fix this, I started by removing the kmod SUBDIR line in the Makefile. 

libsecadm.so.0 would also not install, so on the host, I ran: `install -s -o root -g wheel -m 444     {$secadm_src}/libsecadm/obj/libsecadm.so.0 {$basejail_root}/usr/lib`

Once back in the jail, I ran: `install -o root -g wheel -m 755 {$secadm_src}/secadm/obj/secadm /usr/local/sbin/`

That seems to get secadm working properly.

**Comment by opntr** [comment]
Hi!

Try install only the libsecadm and secadm.
cd libsecadm
make
make install
cd ../secadm
make
make install

Btw, please fill a pr in secadm's github repo about the issue.

**Comment by umpc** [comment]
Hello,

Only the `make install` commands do not work, and because of the read-only basejail.

After thinking about this for a bit, there might not be a worthwhile solution, other than a simple script or function that takes a basejail, or jail root argument and then copies the needed files to the basejail, or to a specific jail, from the host. But I realize that this isn't Ubuntu. :p

The only reason that this became an issue for me was because I couldn't find documentation saying that secadm needed to be installed into each jail individually. When the pkg install failed due to the permissions error, I accidentally assumed that it did not need to be installed into each jail separately, simply because it was running on the host and the install failed inside of the jail.

I can see now that this was really just a novice mistake, but I feel that adding simple clarification about the need to install secadm into each jail individually in the README would save others' time. If I have some time later today, or tomorrow, I'll write a simple paragraph to add to the README.
