### ISSUE TITLE
secadm kernel module fails to register at loading (HBSD-11 STABLE)

### ISSUE THREAD

**Issue by angelescuo** [HardenedBSD/secadm#33]
I have installed last hbsd-11 in vbox.
After installing secadm from packages I have added a valid rule and tryed to start secadm.
Loading of secadm failed because secadm-kmod failed to register ( was built for another kernel)
Cloned secadm frrom github, compiled and installed.
secadm started succesfully after loaded built secadm-kmod.

**Comment by lattera** [comment]
The kernel version was bumped. I'm doing a new package build now. T-Minus 40 hours till the package repo is published.

**Comment by mekanix** [comment]
I have this same issue with this install:
```
root@marvin:~ # uname -a
FreeBSD marvin.lab.tilda.center 11.0-STABLE-HBSD FreeBSD 11.0-STABLE-HBSD #0 : Fri Mar 10 19:49:06 UTC 2017     root@updater-01:/usr/obj/usr/src/sys/HARDENEDBSD  amd64
```

Compiling from ports doesn't help.

**Comment by lattera** [comment]
What does dmesg tell you when you try to run `kldload secadm`?

**Comment by lattera** [comment]
When you built from ports, did your /usr/src match your installed kernel?

**Comment by mekanix** [comment]
```
/usr/src % git branch
* hardened/11-stable/master
```
Is that appropriate?

**Comment by lattera** [comment]
`git fetch; git status`

**Comment by mekanix** [comment]
I did a --deph=1 clone, so that's going to take a while. Is it possible that shallow git clone is the cause?

**Comment by lattera** [comment]
Chances are that what's in /usr/src is newer than your installed kernel. You probably need to build/install world and kernel first.

**Comment by mekanix** [comment]
OK, I'll write here once everything is installed how it went

**Comment by mekanix** [comment]
It works after recompiling everything. Thank you!
